[package]
name = "our_fractal_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.9.0"
speculate = "0.1.2"
rstest = "0.12.0"