version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: rustup install nightly
          command: rustup install nightly
      - run:
          name: Run test
          command: "cargo test"
      - run:
          name: cargo install grcov
          command: |
            sudo gem install coveralls-lcov
            cargo install grcov
      - run:
          name: Run coverage
          command: |
            cargo +nightly build --verbose
            cargo +nightly test --verbose

            grcov ./target/debug/deps -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info
            genhtml -o report/ --show-details --highlight --ignore-errors source --legend lcov.info