version: 2.1

jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run: cargo --version
      - run:
          name: rustup install nightly
          command: rustup install nightly
      - run:
          name: Run test
          command: "cargo test"
      - run:
          name: Run coverage
          command: bash test_coverage.sh